# Generated by Django 6.0.1 on 2026-01-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('org_admin', 'Organization Admin'), ('user', 'User'), ('security_analyst', 'Security Analyst'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
