# Generated by Django 6.0.1 on 2026-01-19 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Email address of the organization admin to invite', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='admin_first_name',
            field=models.CharField(blank=True, help_text='First name of the organization admin', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='admin_last_name',
            field=models.CharField(blank=True, help_text='Last name of the organization admin', max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.organization')),
            ],
            options={
                'db_table': 'organization_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='organizatio_token_779f11_idx'), models.Index(fields=['email', 'used'], name='organizatio_email_702895_idx')],
            },
        ),
    ]
