# Generated by Django 6.0.1 on 2026-01-16 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('asset_type', models.CharField(choices=[('domain', 'Domain'), ('subdomain', 'Subdomain'), ('ip', 'IP Address'), ('api', 'API Endpoint')], db_index=True, max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('discovery_source', models.CharField(help_text='Source of discovery (amass, subfinder, crt.sh, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='accounts.organization')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='AssetChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('new', 'New Asset'), ('removed', 'Asset Removed'), ('status_change', 'Status Changed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='assets.asset')),
                ('scan_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_changes', to='scans.scanrun')),
            ],
            options={
                'db_table': 'asset_changes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssetMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('business_function', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='assets.asset')),
            ],
            options={
                'db_table': 'asset_metadata',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='assets.asset')),
            ],
            options={
                'db_table': 'ownership',
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'asset_type'], name='assets_organiz_2f92be_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'is_active'], name='assets_organiz_12ffd1_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['name'], name='assets_name_74a4a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('organization', 'name', 'asset_type')},
        ),
        migrations.AddIndex(
            model_name='assetchange',
            index=models.Index(fields=['asset', 'timestamp'], name='asset_chang_asset_i_e18970_idx'),
        ),
        migrations.AddIndex(
            model_name='assetchange',
            index=models.Index(fields=['change_type', 'timestamp'], name='asset_chang_change__3840f1_idx'),
        ),
    ]
