# Generated by Django 6.0.1 on 2026-01-16 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='function',
            field=models.CharField(blank=True, choices=[('customer_facing', 'Customer-Facing'), ('internal', 'Internal'), ('partner', 'Partner'), ('development', 'Development')], max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_unknown',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag for unknown/unmanaged assets'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sensitivity',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='assetchange',
            name='details',
            field=models.JSONField(default=dict, help_text='Additional change details'),
        ),
        migrations.AlterField(
            model_name='assetchange',
            name='change_type',
            field=models.CharField(choices=[('new', 'New Asset'), ('removed', 'Asset Removed'), ('status_change', 'Status Changed'), ('service_exposed', 'New Service Exposed')], max_length=20),
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='accounts.organization')),
            ],
            options={
                'db_table': 'asset_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'is_unknown'], name='assets_organiz_1db440_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together={('organization', 'name')},
        ),
    ]
