# Generated by Django 6.0.1 on 2026-01-17 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('assets', '0002_asset_function_asset_is_unknown_asset_sensitivity_and_more'),
        ('scans', '0003_alter_scanrun_status_scheduleddiscovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='assetmetadata',
            options={'verbose_name': 'Asset Metadata', 'verbose_name_plural': 'Asset Metadata'},
        ),
        migrations.AlterModelOptions(
            name='ownership',
            options={'verbose_name': 'Asset Ownership', 'verbose_name_plural': 'Asset Ownerships'},
        ),
        migrations.RemoveField(
            model_name='assetmetadata',
            name='business_function',
        ),
        migrations.RemoveField(
            model_name='assetmetadata',
            name='criticality',
        ),
        migrations.RemoveField(
            model_name='assetmetadata',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assetmetadata',
            name='tags',
        ),
        migrations.AddField(
            model_name='assetmetadata',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional asset metadata'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('domain', 'Domain'), ('subdomain', 'Subdomain'), ('ip', 'IP Address'), ('api', 'API Endpoint'), ('web_service', 'Web Service'), ('web_application', 'Web Application'), ('port', 'Exposed Port'), ('service', 'Service')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assetchange',
            name='change_type',
            field=models.CharField(choices=[('new', 'New Asset'), ('removed', 'Asset Removed'), ('status_change', 'Status Change'), ('port_change', 'Port Change'), ('service_change', 'Service Change'), ('header_change', 'Header Change'), ('certificate_change', 'Certificate Change'), ('subdomain_change', 'Subdomain Change'), ('ip_change', 'IP Address Change'), ('metadata_change', 'Metadata Change')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assetchange',
            name='details',
            field=models.JSONField(default=dict, help_text='Change details'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('port_change', 'Port Change'), ('service_change', 'Service Change'), ('header_change', 'Header Change'), ('certificate_change', 'Certificate Change'), ('subdomain_change', 'Subdomain Change'), ('ip_change', 'IP Address Change'), ('new_asset', 'New Asset Discovered'), ('asset_removed', 'Asset Removed'), ('status_change', 'Status Change'), ('metadata_change', 'Metadata Change')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict, help_text='Additional notification details')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.organization')),
                ('scan_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='scans.scanrun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_read', '-created_at'], name='notificatio_organiz_cdf7d8_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['asset', '-created_at'], name='notificatio_asset_i_795bdf_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_498289_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_data', models.JSONField(default=dict, help_text='Complete scan data including ports, headers, certificates, etc.')),
                ('open_ports', models.JSONField(default=list, help_text='List of open ports')),
                ('services', models.JSONField(default=dict, help_text='Services detected on ports')),
                ('headers', models.JSONField(default=dict, help_text='HTTP headers')),
                ('certificate_info', models.JSONField(default=dict, help_text='SSL/TLS certificate information')),
                ('ip_addresses', models.JSONField(default=list, help_text='Resolved IP addresses')),
                ('subdomains', models.JSONField(default=list, help_text='Discovered subdomains')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_snapshots', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_snapshots', to='accounts.organization')),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_snapshots', to='scans.scanrun')),
            ],
            options={
                'db_table': 'scan_snapshots',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['asset', '-scanned_at'], name='scan_snapsh_asset_i_01a7e3_idx'), models.Index(fields=['organization', '-scanned_at'], name='scan_snapsh_organiz_a91843_idx'), models.Index(fields=['scan_run'], name='scan_snapsh_scan_ru_d61580_idx')],
            },
        ),
    ]
