# Generated by Django 6.0.1 on 2026-01-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_organiz_cdf7d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_c4e471_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_asset_i_795bdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_498289_idx',
        ),
        migrations.RemoveIndex(
            model_name='scansnapshot',
            name='scan_snapsh_asset_i_01a7e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='scansnapshot',
            name='scan_snapsh_organiz_a91843_idx',
        ),
        migrations.RemoveIndex(
            model_name='scansnapshot',
            name='scan_snapsh_scan_ru_d61580_idx',
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='assetmetadata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ownership',
            options={},
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assetchange',
            name='change_type',
            field=models.CharField(choices=[('new', 'New Asset'), ('removed', 'Asset Removed'), ('status_change', 'Status Changed'), ('service_exposed', 'New Service Exposed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assetchange',
            name='details',
            field=models.JSONField(default=dict, help_text='Additional change details'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='scansnapshot',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='scansnapshot',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='scansnapshot',
            name='scan_run',
        ),
        migrations.AddField(
            model_name='asset',
            name='criticality',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', help_text='Asset criticality level', max_length=20),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'criticality'], name='assets_organ_crit_idx'),
        ),
    ]
