# Generated by Django 6.0.1 on 2026-01-20 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_admin_email_and_more'),
        ('assets', '0004_add_criticality_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable all alerts for this organization')),
                ('email_enabled', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('email_recipients', models.JSONField(default=list, help_text='List of email addresses to receive alerts')),
                ('notify_on_low', models.BooleanField(default=False, help_text='Send notifications for low severity events')),
                ('notify_on_medium', models.BooleanField(default=True, help_text='Send notifications for medium severity events')),
                ('notify_on_high', models.BooleanField(default=True, help_text='Send notifications for high severity events')),
                ('notify_on_critical', models.BooleanField(default=True, help_text='Send notifications for critical severity events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Configuration',
                'verbose_name_plural': 'Alert Configurations',
                'db_table': 'alert_configurations',
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Rule name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Rule description')),
                ('rule_type', models.CharField(choices=[('asset_count_threshold', 'Asset Count Threshold'), ('new_assets_threshold', 'New Assets Threshold'), ('unknown_assets_threshold', 'Unknown Assets Threshold'), ('vulnerability_count_threshold', 'Vulnerability Count Threshold'), ('risk_score_threshold', 'Risk Score Threshold')], max_length=50)),
                ('operator', models.CharField(choices=[('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('equals', 'Equals'), ('greater_than_or_equal', 'Greater Than Or Equal'), ('less_than_or_equal', 'Less Than Or Equal')], max_length=30)),
                ('threshold_value', models.FloatField(help_text='Threshold value to compare against')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable this rule')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('conditions', models.JSONField(default=dict, help_text='Additional rule conditions (e.g., asset_type, time_window)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alert_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_department', models.CharField(blank=True, max_length=255)),
                ('new_department', models.CharField(blank=True, max_length=255)),
                ('old_owner_name', models.CharField(blank=True, max_length=255)),
                ('new_owner_name', models.CharField(blank=True, max_length=255)),
                ('old_owner_email', models.EmailField(blank=True, max_length=254)),
                ('new_owner_email', models.EmailField(blank=True, max_length=254)),
                ('change_reason', models.TextField(blank=True, help_text='Reason for ownership change')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ownership_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scan_run',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='ScanSnapshot',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_organiz_73f8e2_idx',
            old_name='assets_organ_crit_idx',
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_config', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='ownershiphistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='ownershiphistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'enabled'], name='alert_rules_organiz_7c892a_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiphistory',
            index=models.Index(fields=['asset', 'changed_at'], name='ownership_h_asset_i_bfa1ac_idx'),
        ),
    ]
