# Generated by Django 6.0.1 on 2026-01-16 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('ssl', 'SSL/TLS'), ('port', 'Open Port'), ('service', 'Service Vulnerability'), ('web', 'Web Application'), ('api', 'API Vulnerability'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], db_index=True, max_length=20)),
                ('cvss', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('evidence', models.JSONField(default=dict, help_text='Raw evidence from scanner')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('risk_accepted', 'Risk Accepted')], db_index=True, default='open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='assets.asset')),
            ],
            options={
                'db_table': 'vulnerabilities',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['asset', 'severity'], name='vulnerabili_asset_i_5324f0_idx'), models.Index(fields=['asset', 'status'], name='vulnerabili_asset_i_f20c7e_idx'), models.Index(fields=['severity', 'status'], name='vulnerabili_severit_8aab25_idx')],
            },
        ),
    ]
