# Generated by Django 6.0.1 on 2026-01-16 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('discovery', 'Asset Discovery'), ('port', 'Port Scan'), ('vulnerability', 'Vulnerability Scan'), ('ssl', 'SSL Check')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict, help_text='Scan configuration')),
                ('results', models.JSONField(default=dict, help_text='Scan results')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to='accounts.organization')),
            ],
            options={
                'db_table': 'scan_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'scan_type'], name='scan_runs_organiz_e4b6c1_idx'), models.Index(fields=['organization', 'status'], name='scan_runs_organiz_08781f_idx')],
            },
        ),
    ]
