# Generated by Django 6.0.1 on 2026-01-17 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('scans', '0002_alter_scanrun_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduledDiscovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text='Domain to discover assets for', max_length=255)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('enable_port_scan', models.BooleanField(default=False, help_text='Enable port scanning')),
                ('enable_service_detection', models.BooleanField(default=False, help_text='Enable service detection')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the scheduled discovery is active')),
                ('last_run', models.DateTimeField(blank=True, help_text='Last time the discovery was run', null=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='Next scheduled run time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discoveries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_discoveries', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Scheduled Discovery',
                'verbose_name_plural': 'Scheduled Discoveries',
                'db_table': 'scheduled_discoveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='scheduled_d_organiz_5c304c_idx'), models.Index(fields=['next_run'], name='scheduled_d_next_ru_130877_idx')],
            },
        ),
    ]
