# Generated by Django 5.0.1 on 2026-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_alter_scanrun_status_scheduleddiscovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
    ]
