# Generated by Django 6.0.1 on 2026-01-16 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('mfa_enable', 'MFA Enabled'), ('mfa_disable', 'MFA Disabled'), ('role_change', 'Role Changed'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('org_create', 'Organization Created'), ('org_update', 'Organization Updated'), ('asset_update', 'Asset Updated'), ('vulnerability_update', 'Vulnerability Updated'), ('risk_recalculate', 'Risk Recalculated')], max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['organization', 'timestamp'], name='audit_logs_organiz_9c8c67_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx')],
            },
        ),
    ]
