# Generated by Django 6.0.1 on 2026-01-16 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('explanation', models.JSONField(default=dict, help_text='Explainable risk calculation breakdown')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vulnerability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='vulnerabilities.vulnerability')),
            ],
            options={
                'db_table': 'risk_scores',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['score'], name='risk_scores_score_9d8e72_idx')],
            },
        ),
    ]
